modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="ottercraft"
version="0.0.2.0"
displayName="Ottercraft"
credits=""
description='''
Adds otters to Minecraft. What more could you ask for?
'''
